### ISSUE TITLE
Not updated for new cFS versions

### ISSUE THREAD

**Issue by Jkillelea** [nasa/SC#3] opened 2022-04-05 19:43 UTC
The cFS API has changed substantially since the last commit to this repo and the SC app no longer compiles with new versions of cFS.

**Comment by Nodraak** [comment] 2022-04-06 09:56
Duplicate of https://github.com/nasa/SC/issues/2.

**Comment by skliper** [comment] 2022-04-06 12:42
Updated release is imminent...

**Comment by skliper** [comment] 2022-05-06 18:55
Updated for Caelum in ae2d615e7431d430950fd25ccc7e85587c03ad95 and Draco in a7227270e4146e7857d673ed2ab7dff173d43dfd.

**Closed by skliper** 2022-05-06 18:55 UTC
Labels: bug
